### ISSUE TITLE
Automatically add all booked experiences to the Kudoz Google calendar?

### ISSUE THREAD

**Issue by jonaspiet** [InWithForward/sharetribe-old#100]
Right now we are manually adding booked experiences to the 'kudoer & Circle interactions' calendar, for the team to keep track of what happens. Is there a way to have them automatically added to this google calendar once a booking is confirmed?

@samuelreh If this is less then an hour, please build this!

**Comment by samuelreh** [comment]
Hey Jonas, Unfortunatly, I don't think this one fits in the less than an hour timebox. Probably more on the scale of 2-4.

**Comment by jonaspiet** [comment]
ok thanks for the quick reply!
let's not prioritize if for now then.
