### ISSUE TITLE
Display multiple videos on a user profile

### ISSUE THREAD

**Issue by jonaspiet** [InWithForward/sharetribe-old#101]
As a Kudoer, I want to be able to see several videos on my profile. These are videos about me, other then the mediafiles from experiences. As an admin, I want to easily display new videos on profiles.

(note we also mentioned  the auto display function of media files from the app #70)

Really nice option: 
1) some kind of caroussel 
more work for Sam to change profile > is there even such an object we can use?
do we want to upload the videos into the sharetribe database from the phone?

Things we can do now:
....................................................................................................
2) Use the existing youtube field with playlists for each Kudoer (possible already)
Settings: most recent video first, and autoplay; so that all videos are played in line. To test - go to end of video and next one in playlist is played automatically.
example: https://catalogue.kudoz.ca/kudoztester
playlist link: https://www.youtube.com/watch?v=5Zg-C8AAIGg&list=PLb9dz_i1yPCCoa40vfj7qrdyNsdUO1PGI 

3) We add a (few admin enabled) video fields to the profile (5mins work)
get videos from youtube 

4) Make textboxes HTML enabled (bit of work for Sam)
so we can paste in a URL link to their youtube page 

@samuelreh If we wanted to build (1) later, which easy option would be preferred from a data management perspective?

**Comment by mkasdani** [comment]
Hey Jonas,

What do you mean with number 2) Use existing playlist for each Kudoer. Take this playlist link for John as an example: https://www.youtube.com/watch?v=py7utE3d_NA&list=PLaGw4KIIyV0DfznBYzx1V9v_OdpNJS5pn&index=1

That link was copied from the most recent video (there are 6 total), and it's in autoplay.
They way I got the link: copied from the URL bar, or click "share" just under the video, and copied the link.

I tried pasting it in the YouTube link field in the profile, but it only shows the first video, and not the rest of the videos in the playlist.

Pls let me know if I have gotten the wrong link, and where to find the right link.

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#25
