### ISSUE TITLE
Titling experiences that have 'expired'

### ISSUE THREAD

**Issue by AndieFro** [InWithForward/sharetribe-old#102]
Right now When an experience goes from 'expiring' to expired it is listed in the 'View Experiences' page as 'canceled'. This is confusing as it makes it seem like the experience was cancelled by either the host or the Kudoer, not expired.

ask: would it be possible to change the designation of experiences in the status field to 'expired' instead of 'cancelled' reserving 'cancelled' designation for eperiences that were actually cancelled by a host or Kudoer?

![image](https://cloud.githubusercontent.com/assets/16580556/13090429/780e818c-d4aa-11e5-962a-5f25cb8f141d.png)

**Comment by AndieFro** [comment]
@jonaspiet @lisajoytrick

**Comment by jonaspiet** [comment]
@samuelreh is this a simple one? i.e. less then an hour?
if so, please build it, after the new metrics features (interests and goals)

So we can keep track of host behaviour: do they actively cancel or do they not respond.

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#26
