### ISSUE TITLE
Wrong name appearing when replying to messages

### ISSUE THREAD

**Issue by AndieFro** [InWithForward/sharetribe-old#104]
Not a huge issue but wanted to flag it

Yesterday John (woods) was sending a message to another user Aaron Pietras and the message box said "send a note to John" when it was John sending the note to Aaron. I was able to replicate it by going through my messages but it didn't happen with all of them, I think it's just when I respond to a message that's been sent to me, not in a message thread that I started with a user.

Me sending Shiela a note
![image](https://cloud.githubusercontent.com/assets/16580556/13118100/8199ddf2-d557-11e5-9753-93f160fbd47a.png)

@jonaspiet

**Comment by AndieFro** [comment]
User Alexander Dirksen also reported this issue to me today

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#28
