### ISSUE TITLE
Getting feedback for closed listings

### ISSUE THREAD

**Issue by AndieFro** [InWithForward/sharetribe-old#105]
When a host closes their listing we need to collect data to find out why. Right now it's a one-click option underneath the 'edit listing' option and it just removes it right away.

As a host when I select 'Close listing' I should be taken to a confirmation page warning me that I am closing my listing and asking me why.

eg: 

You have closed this experience. Nothing will be deleted, you've just removed it from the catalogue and everything will be where you left it when you come back. 

It would be great if you could let us know
- This is just temporary: I'm just really busy right now, going on vacation or life is in the way
- This is permanent, I don't really want to host this particular experience again
- This is permanent, I don't want to be a Kudoz host at all anymore

To re-open this listing again visit your profile and click on the "view also closed", select this experience and click on "Re-open this listing"

(the wording maybe should be more chipper and engageing than a boring "Why are you closing this listing...)

What it looks like now
![image](https://cloud.githubusercontent.com/assets/16580556/13127743/fbd4f376-d585-11e5-8956-56b0e9667f95.png)
to
![image](https://cloud.githubusercontent.com/assets/16580556/13127806/6840ac08-d586-11e5-8d2c-f53a87ee672a.png)

An example of what might happen
<img width="807" alt="close account" src="https://cloud.githubusercontent.com/assets/16580556/13127828/77b5b5c0-d586-11e5-8f93-587794a46c7c.png">

**Comment by AndieFro** [comment]
@jonaspiet This isn't a super high priority but I think we need it in the future as I won't be able to call every host that closes their account

**Comment by jonaspiet** [comment]
I agree we need this, but let's hold off building for now.
I'd also change the wording a little bit
Out of curiousity: have many hosts close their listing? 


........................................................................................................................
You are about to close your experience [experience title]. Nothing will be deleted, but we'll take your experience out of the Kudoz catalogue for now. You can reopen it if you want. 

Please let us know why you're closing your experience...
[  ]  This is temporary: I'm really busy, going on vacation or life is in the way
[  ]  This is permanent, I don't want to host [experience title] anymore
[  ]  This is permanent, I don't want to be a Kudoz host anymore
[  ]  Something else: [open text field]

To re-open your experience, visit your profile and click on "view also closed", select this experience, and click on "Re-open this listing".

**Comment by AndieFro** [comment]
Yup, I agree it's not priority and that the wording is not quite right. I might ask John to help me when we do decide to build it, he has a very charming way of writing things like this.

We have not had that many but just this week I've had to close Milena's and Nick Janzen asked me how to take his down which made me realize this would be great to have.

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#29
