### ISSUE TITLE
Changing order of pictures in experience listing

### ISSUE THREAD

**Issue by AndieFro** [InWithForward/sharetribe-old#108]
Changing order of pictures in experience listing, when uploading new ones.

Right now pictures show up in the order they were uploaded.When we go back at a later date and we want to make the most recently added photo appear first, we have to delete all the old photos until the photo we want appears as the main picture.

Is there a way to drag photos around so the best one appears first without deleting older photos?

Potential quick fix:
show last uploaded image first - so we can add a 'special offer' front image

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#30
