### ISSUE TITLE
messages from sharetribe going to receiver's spam folder

### ISSUE THREAD

**Issue by jonaspiet** [InWithForward/sharetribe-old#110]
@samuelreh 
How we can send emails that are less likely to go into junk folders? 
Maybe by...
- title outgoing emails differently?
- prompt the host in person?
- ...?
 
@AndieFro notices a trend of hosts not even seeing the  first email requesting an experience

**Comment by samuelreh** [comment]
Hey @AndieFro, Which hosts in particular? Do we know which email service they're using?

**Comment by AndieFro** [comment]
@samuelreh It's been Gmail. Anna Wexler of the doggy daycare experience, John Woods Jingle Experience and I believe Sheila Maier with the cake decorating experience

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#31
