### ISSUE TITLE
Make experience part of multiple categories

### ISSUE THREAD

**Issue by AndieFro** [InWithForward/sharetribe-old#117]
Would it be possible for experiences to appear under multiple categories? For example 'Going on a nature walk with Ladybug the dog' Should be under animal hobbies AND outdoors and nature. 

For hosts, their experience will be searchable by more people. For Kudoers they might miss an experience they are interested because an experience is only showingup under one category.

![image](https://cloud.githubusercontent.com/assets/16580556/13443174/ccc52964-dfb4-11e5-952b-16472295f4f1.png)

![image](https://cloud.githubusercontent.com/assets/16580556/13443202/ec0f0e98-dfb4-11e5-9dfd-02faaaa45985.png)

**Comment by AndieFro** [comment]
@jonaspiet not a top priority but definitly would make the experiences more easily searchable and organized

**Comment by AndieFro** [comment]
@samuelreh This is also kind of a bug now, there are experiences that aren't showing up under the categories that they are sorted under. Could this be fixed even if we can't file experiences under multiple categories just yet.

This is an issue because a lot of users browse the catalogue by going through categories so experiences are going completely un-noticed. 

There are multiple instances of this, I'm just using the example of 'basic Cake Decorating'
![image](https://cloud.githubusercontent.com/assets/16580556/13471376/273370ee-e065-11e5-9471-98d8b91e0b40.png)

I've saved it under the category 'food'. (ideally it would go under 'food' AND 'making things')
![image](https://cloud.githubusercontent.com/assets/16580556/13471334/f7dc087e-e064-11e5-99f9-fde390bc9510.png)

When we visit the food category basic cake decorating is nowhere to be found
![image](https://cloud.githubusercontent.com/assets/16580556/13471369/22dac600-e065-11e5-8715-d126dd0791c0.png)

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#32
