### ISSUE TITLE
Share Kudoer's number with host on booking

### ISSUE THREAD

**Issue by samuelreh** [InWithForward/sharetribe-old#127]
We'd like to share the Kudoer's number with a host when the experience is booked.
The problem with the current system for doing this is that the Kudoer might not check their reminder email and click the button to share their number.

On Kudoer signup, let's add a checkbox:

 [ ] I will share my number with the host

Then on every experience booking, let's add the Kudoer's number to the email that goes out to the host.

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#35
