### ISSUE TITLE
Map of experience listings & Map of user locations

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe-old#13]
This one there already is a map view for experience listings:
https://catalogue.kudoz.ca/en?view=map
 

It would be helpful for us to see where our users are located and where our listings are located across the lower mainland. Can sharetribe display this data or can we use a custom google map for it? We could manually add in the addresses ourselves but if there is a way to get this from sharetribe that would be great.

Maps should be viewable by our team only - not public.

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#4
