### ISSUE TITLE
edit experiences - fields not appearring

### ISSUE THREAD

**Issue by AndieFro** [InWithForward/sharetribe-old#130]
There are two experiences that don't show all the fields when I hit 'edit'. Only a few of the fields and the calendar show up.

https://catalogue.kudoz.ca/en/listings/239-visiting-at-a-daycare

https://catalogue.kudoz.ca/en/listings/51-learning-and-teaching-with-childrens-books

![image](https://cloud.githubusercontent.com/assets/16580556/13690074/808943c0-e6e2-11e5-95c3-f11702412622.png)

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#36
