### ISSUE TITLE
Reasons to choose an experience (make it into multiple choice)

### ISSUE THREAD

**Issue by mkasdani** [InWithForward/sharetribe-old#132]
We have noticed that Kudoers either want to choose multiple reasons of why they choose an experience (e.g. "I want to do this experience because it's fun AND I want to challenge myself") or they miss it entirely as a choice they need to make because the answers are hidden inside the dropdown menu. They went ahead and clicked "Confirm" to go to the next page.

Can we change it to multiple choice with tick boxes pls? So they see all of the choices.
![screenshot 2016-03-11 15 01 08](https://cloud.githubusercontent.com/assets/16656508/13717990/8ae02d3a-e79a-11e5-89cc-eb3189c5d7d7.png)

**Comment by mkasdani** [comment]
@samuelreh today I had another interaction with a Kudoer who got totally confused with this feature. Didn't know that it's a drop-down menu, and ended up skipping it by clicking "confirm". It also showed up as a Jackpot-like interface on his iPhone (iPhone 4 or 5), which was confusing for him. 

And... where does this information go? I didn't find it shown anywhere.

Example of a jackpot-like interface on Iphone:
![dropdown-iphone](https://cloud.githubusercontent.com/assets/16656508/13895807/ddb0fcba-ed35-11e5-9b03-a77f0cd95965.png)

**Comment by lisajoytrick** [comment]
This information feeds into the app and is part of check in and check out. @mkasdani - I'm moving this to "needs more planning" so we can discuss alternatives. I don't know how a multiple choice would work with the app.
