### ISSUE TITLE
SMS reminder notification to Kudoer

### ISSUE THREAD

**Issue by samuelreh** [InWithForward/sharetribe-old#133]
SMS reminder to Kudoer before experience (24 hr before)

**Comment by samuelreh** [comment]
@jonaspiet can you attach the copy?

**Comment by jonaspiet** [comment]
copy:

Getting ready for your experience [title] tomorrow at [time], at [address]?
Any questions: call us at (604) 862-5836

**Comment by mkasdani** [comment]
Can we include:
Don't forget to use Nest Forms to check-in before you start your experience, take pictures during your experience, and check-out when you're done.

**Comment by samuelreh** [comment]
@mkasdani yep. All done.

**Comment by jonaspiet** [comment]
Hi [user], getting ready for your experience [title] tomorrow at [time], at
[address]?
Any questions: call us at (604) 862-5836.


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by mkasdani** [comment]
Sorry, I am confused. Which one is the final text? Does it include the reminder for check-in and check-out?

**Comment by jonaspiet** [comment]
@mkasdani : you wanted to add the second sentence. In my opinion it's too long and too far ahead to  remind to checkin. But let's go with this - slighty streamlined - verison.

Hi [user], getting ready for your experience [title] tomorrow at [time], at [address]? Any questions: call us at (604) 862-5836. Don't forget to check-in before you start, take pictures during your experience, and check-out after.

**Comment by samuelreh** [comment]
@jonaspiet Updated the copy.

**Comment by mkasdani** [comment]
@jonaspiet: I agree it's too far ahead (24 hours before the experience). 

Can we then design an sms reminder one hour before the start of the experience for check-in and check out, BOTH **to Kudoers and to Hosts**? Sending text messages to remind them to check-in/ out manually has taken a chunk of our time, and so far, we have low success rate (the majority of experiences do not have any pictures captured and sent to us, for some reasons). I am going to follow up  on the reasons Kudoers/ Hosts did not take pictures to understand the issue more.

**Comment by lisajoytrick** [comment]
bug 
Dimitri booked Highland Dance Extravaganza on 14 Apr for april 26
cancelled on 21 Apr 2016
still received reminder sms message on april 25

**Comment by samuelreh** [comment]
@lisajoytrick nice catch, should be fixed now.
