### ISSUE TITLE
Messages not marked as read

### ISSUE THREAD

**Issue by mkasdani** [InWithForward/sharetribe-old#140]
I logged in as a Kudoer (Umete Bayatli, email: umetebayatli@gmail.com). I saw that I have 2 unread messages. I clicked on the messages (read them), then went back to my the main page of my messages, but the messages are still shown as unread (there's the number 2 on top, next to the envelope icon), and highlighted as unread.

Logged in, saw this icon for 2 unread messages:
![screenshot 2016-03-17 16 57 47](https://cloud.githubusercontent.com/assets/16656508/13864763/ade2aa80-ec61-11e5-8c85-a9b48a1651c7.png)

Clicked the messages and read them:
![screenshot 2016-03-17 16 57 57](https://cloud.githubusercontent.com/assets/16656508/13864784/c0975f40-ec61-11e5-8cfb-1e5aeb8bd5c3.png)

Still saw the messages as unread (see the 'number 2' next to the envelope icon, and messages highlighted as unread)
![screenshot 2016-03-17 16 58 07](https://cloud.githubusercontent.com/assets/16656508/13864800/d9ccfb96-ec61-11e5-84e8-d42984c58f90.png)

**Comment by samuelreh** [comment]
@mkasdani does it change if you reload the page? Might be cached in the browser.

**Comment by mkasdani** [comment]
@samuelreh I tried reloading and used a different browser (firefox and chrome), and used my phone. Nothing worked.

**Comment by jonaspiet** [comment]
thanks for documenting Yani. Good to know but this is something to park for
now - it's not so imporant or urgent.


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#39
