### ISSUE TITLE
YouTube link on Kudoer's profile can't be erased and updated

### ISSUE THREAD

**Issue by mkasdani** [InWithForward/sharetribe-old#142]
I am logged in as an admin (using Profile Builder account, yani@kudoz.ca). I tried to update the Youtube link in "Videos I am featured in" field on a Kudoer's profile page (Richard K: https://catalogue.kudoz.ca/richard) I tried many times to delete the URL, and click "Save Information", but the video still appeared there.

I then wrote a period (just a dot) in the field, and then click "Save Information". On Richard's profile page, it shows as a video thumbnail. But because it's not a real URL, the play button doesn't work. 

It might be a bug that we can't have the field empty after putting something in, and it has to be filled with a character, even just a dot. 

Screenshot of the Richard's profile page, from the back-end/ "Edit Profile" page where the I typed the dot as a URL:
![screenshot 2016-03-23 09 07 49](https://cloud.githubusercontent.com/assets/16656508/13991829/d1047092-f0d6-11e5-96fc-3b5ea7c71658.png)

Screenshot of Richard's profile page (video doesn't work/ can't play because it's just a dot. But there's no way to leave the field empty)
![screenshot 2016-03-23 09 07 32](https://cloud.githubusercontent.com/assets/16656508/13991839/d810b40e-f0d6-11e5-8f09-c8fbfa2ac15b.png)

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#41
