### ISSUE TITLE
Giving feedback when cancelling an experience

### ISSUE THREAD

**Issue by AndieFro** [InWithForward/sharetribe-old#145]
When a host or kudoer cancels an experience the same logic happens when it's marked as complete. This means if a user wants to give a reason for cancelling to the other user than it appears as feedback on their profile

see: Shurl cancelling on Zach OR Umete cancelling on Christina

![image](https://cloud.githubusercontent.com/assets/16580556/14030228/cec1dafc-f1c3-11e5-9102-fd45866c1685.png)

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#42
