### ISSUE TITLE
Editing/deleting feedback

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe-old#156]
We have situations where a host has given cancellation details as feedback and this is currently displaying on a users' profile. We want to delete or edit these so the profile is easier to understand. Can you help us figure out how we could do this?

**Comment by samuelreh** [comment]
we could display all the feedbacks given in a new admin panel? From there you could delete or edit them. Probably wouldn't take more than 2 hours to display them and add actions for deleting and editing/updating.

If it's just a one time thing, I can go into DB and delete the feedback.

**Comment by lisajoytrick** [comment]
What about if a user could edit their own feedback and we can use the skeleton key?

**Comment by samuelreh** [comment]
@lisajoytrick sounds good, would probably take about 1.5 hours.

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#43
