### ISSUE TITLE
Revising "your host can't make it" email message

### ISSUE THREAD

**Issue by mkasdani** [InWithForward/sharetribe-old#159]
Right now, when Hosts reject Kudoer's booking because the schedule doesn't work, the system sends out a very short message that says:
![screenshot 2016-04-13 17 10 23](https://cloud.githubusercontent.com/assets/16656508/14513247/a0077db6-019a-11e6-86ab-5610ba8e604b.png)

It's quite confusing right now because Kudoers is booking multiple experiences at the same time, and they don't know which one has been rejected. Can we add more details like:
"Your host, [host name], can't make the days and time you have requested. Can you rebook [name of experience]?" Then "Rebook" button that goes directly to the experience calendar/ schedule.

**Comment by jonaspiet** [comment]
@lisajoytrick can you add this to the copy?

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#44
