### ISSUE TITLE
Improving sign-up issues for Kudoers (to discuss further)

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe-old#162]
As more people hear about Kudoz and visit the website, interested kudoers are joining the catalogue directly and bypassing the application form so Learning Gurus aren’t getting enough information from them.

This has created a few issues:

1. when they get to the point of choosing a role “kudoer or host” they may not know enough about Kudoz to make the right choice - we need to improve what’s seen on this page

2. without the application form, we don’t know enough about whether or not they would be a good match - we could add an “application” step in the catalogue or add more fields to the profile

3. the “"new member in kudoz” admin email needs more info. Right now it just displays first name and & email - Can we have the full name, role chosen, etc?

As an quick fix for now I planned added a reminder & link to the google form into the page copy on the roles page but when I inserted HTML into the yml file I broke it :(

**Comment by lisajoytrick** [comment]
I've resolved the html problem by using different code in YML. Links need to be structured like this: 
<a href=\"http://linkhere\" target=\"_blank\">link text</a>
* note use of \

**Comment by lisajoytrick** [comment]
since we are halting on signing up new users we can hold on this for now

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#45
