### ISSUE TITLE
Admin efficiencies - marking experiences as complete 

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe-old#163]
A regular piece of work that our curator does is to check the catalogue to make sure completed experiences have been marked as complete so feedback prompting is sent as well as a post experience email with the media. Right now this takes a long time because they have to check experiences page by page to find the ones with time/date passed.

Currently experiences/transactions display by order of latest activity (last message sent, last action taken) but that doesn’t take into account when an experience has been booked a long time ago and confirmed and no one has needed to 

Fixes:
option 1: make 500 items show up on each page so there will only be two pages to check

option 2: make columns sortable so she can filter items with action items (or status booked) to the top

option 3: when an experience time has passed, status changes to expired and item goes to the top of the list so it triggers admin to check to confirm if it happened

**option 4: (best & most complicated!):** when an experience time has passed, the system looks up the media file on AWS and if it's there, it marks experience as compete & adds media file to kudoer's profile.
Message with link to video is sent to:
- all kudoer emails (i.e.: kudoer and circle)  - as part of the feedback message
- the host - as part of the feedback message
- and the learning guru responsible

**Comment by samuelreh** [comment]
option 2: 1 hr (depending on column, but for just status or booked for)
option 3: 2 hrs
option 4 (~ 5.5 hrs): 
 - BG job to check aws: 1hr
 - Display of media file on profile page with JW player: 3 hrs
 - Link to video in emails 1 hrs
 - Email to gurus 0.5 hr

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#3
