### ISSUE TITLE
duplicate password error message

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe-old#165]
When a user tries to use a password that is in use by another user the "another user has this username" message displays which is a bit confusing. It would be nice if this issue had it's own error message that tells them to try a different password.

<img width="1091" alt="screen shot 2016-04-25 at 2 05 15 pm" src="https://cloud.githubusercontent.com/assets/14365107/14800542/28f43a46-0af7-11e6-8d98-d2c7ec0108dc.png">

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#2
