### ISSUE TITLE
Duplicate transaction with multiple request channels

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe-old#166]
This host confirmed the request by SMS and by email which created two active transactions. Can we fix this so doing one action will make the other unavailable? Maybe a "experienced already confirmed" error?

Not sure which order they did (SMS first or email first)

<img width="1085" alt="screen shot 2016-04-25 at 2 48 59 pm" src="https://cloud.githubusercontent.com/assets/14365107/14800674/367e0402-0af8-11e6-8b0c-4c4bfbb85a03.png">

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#1
