### ISSUE TITLE
Feedback from Kudoer for host

### ISSUE THREAD

**Issue by mkasdani** [InWithForward/sharetribe-old#167]
@lisajoytrick This is what Janey, Charlotte and I thought we could try next to prompt Kudoer to leave a better feedback for hosts.
We want to keep things very simple and specific for Kudoers (i.e. "name 3 things"), so that we can try to reach to most of the Kudoers (at least the ones in the middle of the bell curve) regardless of their abilities. This means taking out one box and keeping it only to three. 

In the future, we probably need to include more tools as a template for some of Literalist Kudoers (i.e. Fill in the blank/ complete the sentence for some of the Literalists). 
![feedback-from kudoers](https://cloud.githubusercontent.com/assets/16656508/14840680/4935a07a-0beb-11e6-8e23-66e112b49044.jpg)

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#46
