### ISSUE TITLE
Allow non-admin users to invite friends

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe-old#19]
Currently only admin users can see the "invite new members" button on the menu. Also, if they have the link they enter email addresses but then get an error (see below.)

We would like to allow all logged in users to invite their contacts.

<img width="1032" alt="screen_shot_2015-11-06_at_2 18 59_pm" src="https://cloud.githubusercontent.com/assets/14365107/11010322/ef33a5fc-8492-11e5-88e1-de36d89b1ddb.png">

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#5
