### ISSUE TITLE
permanently deleting a user

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe-old#29]
It seems that when a user is removed from the catalogue they are not fully deleted but just loose access. If someone tries to sign up with that email again they get a message like the one below.

Is there another place within the app that I can permanently delete user accounts or restore a closed account?

<img width="1056" alt="screen shot 2015-11-16 at 11 58 46 am" src="https://cloud.githubusercontent.com/assets/14365107/11197918/7fb84260-8c75-11e5-9cd1-e43ee6e43d2b.png">

**Comment by samuelreh** [comment]
Hmmm. How did you delete them? Using the "Ban User"? This doesnt actually delete the account. It doesn't look like there is a way for admins to delete users. However, users can permanently delete themselves.

I guess the options are: 
- To build in admin functionality to un-ban users, 
- To build the functionality for admins to permanently delete users

**Comment by lisajoytrick** [comment]
We (admin) only needs to be able to un-ban users only. If a user can delete their own account we can take care of the rare account that needs to be deleted from inside the account.

**Comment by lisajoytrick** [comment]
Please quote on feature for admin to un-band user

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#6
