### ISSUE TITLE
data missing in sharetribe

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe-old#37]
Our host curators are reporting lots of data loss issues that are difficult to nail down. I've asked for screenshots and more details but don't have anything else 
- Profile data sometimes disappears when emails or other account is updated
- Seems that 1st learning goal data went missing for all
- Various times that users have added profile or experience data because we have noticed that it does not always save. This could be because the user gets temporarily disconnected on wifi or a local computer issue.

*suggestions*
- can sharetribe save data each time a field is updated instead of based on the save button? If not, can there be several save buttons at various points on a longer form?

- can I see backups or older versions of data so we can see if in fact there was completed fields on the past dates that the users are reporting there was data?

**Comment by samuelreh** [comment]
Looks like custom field values were being cleared when an email was updated. I fixed the bug so this will work now. I have a feeling this was probably the root cause of most of the data inconsistencies.

**Comment by samuelreh** [comment]
it looks to me like the learning goal data is still there for listings.

It's actually not super easy to autosave on data entry. My guess would be about 3 hours of work. I could do a more in depth estimate if we want to go this route. I think it won't be as important now that this bug is fixed.

**Comment by lisajoytrick** [comment]
Ok. I will talk to the team about the autosave but most importantly right
now we are hoping for a way to see our data from several days ago so we can
better figure out what might have been deleted and try to sort out some
missing data issues.

The most pressing data we're concerned about is the profile fields where
someone might have written quite a bit... the like about me field.

- LJ

On Tue, Dec 1, 2015 at 12:22 PM, Samuel Reh <notifications@github.com>
wrote:

> it looks to me like the learning goal data is still there for listings.
>
> It's actually not super easy to autosave on data entry. My guess would be
> about 3 hours of work. I could do a more in depth estimate if we want to go
> this route. I think it won't be as important now that this bug is fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/InWithForward/sharetribe/issues/37#issuecomment-161084603>
> .
>



-- 

Lisa Joy Trick

Interaction Designer, InWithForward

MOBILE 778 809 2780

SKYPE lisajoytrick
TWITTER @lisajoytrick

**Comment by samuelreh** [comment]
I pointed the staging sever (https://kudoz-staging.herokuapp.com/) at a DB
snapshot from 2 days ago. The images won't work, but since those aren't
custom fields, they wouldn't have been lost on prod. You should be able to
find any user fields that were lost in the last two days.

**Comment by lisajoytrick** [comment]
thanks!

**Comment by lisajoytrick** [comment]
Can we look into the autosave option a bit more? Would the time estimate be based on fields or more of a global autosave thing? How accurate was the 3 hr estimate you gave a few months ago? 

We would like to have autosave on the experience listing fields and the profile fields (especially the fields that are unique to the Kudoer user type.)

**Comment by samuelreh** [comment]
@lisajoytrick 3 hrs wouldn't be a global solution, just for one of the flows (profile fields or listing fields). However, after the first flow is finished, the next one would probably be a bit less than 3 hrs. I would have a better sense after completing the first one though.

**Comment by lisajoytrick** [comment]
Hey Sam, we've decided to proceed with autosave for experience listing only. We'll hold on adding it to the profile for now.

**Comment by samuelreh** [comment]
@lisajoytrick autosave feature is up for experiences. Check it out and let me know what ya think.

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#7
