### ISSUE TITLE
change log feature (required for new user types profile)

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe-old#41]
This feature is probably obsolete and replaced with:
> #64 Profile endorsement
> #65 Report Engagement: to Mixpanel

There are a number of fields where we need to be able to see when data has changed, what it was before and what it is now.

Here’s how I suggest this features works:

When a user updates a text field, a message displays by the field saying “updated logged”
(image 1)

When a user updates a dropdown, image/video upload or checkbox field, they have an option to log a note about their update
(image 2)

For administers, there is a section in the admin area called change log which displays username, date/time and details of the update. This page can be filtered by username, date range, field type, etc
(image 3)

![changelog_feature](https://cloud.githubusercontent.com/assets/14365107/11666235/589a781a-9da0-11e5-91b5-9921f17323eb.jpg)

**Comment by samuelreh** [comment]
I'm a little confused on this one? Why not just log all changes? And why is it necessary to tell the user at all? seems a bit overly complex to me.

**Comment by lisajoytrick** [comment]
ya - I see what you mean.

re image 1: I thought it was nice to have the message displayed for transparency purposes as the user may assume that a change over ridges old data but I could be persuaded otherwise.  

re image 2: I understand from the team members who work with our Kudoers that they want to know a bit more about what's going on for someone when they change something that's in a dropdown or checkbox field... like some context around the change. This seemed like the simplest way to capture that contextual info but maybe there's another option?

**Comment by jonaspiet** [comment]
Hey Lisa,
I understand that the problem we're trying to solve is not knowing enough
about what's going when a Kudoer changes a field.

a) is this a real problem? I suspect it is not (yet).
b) if so: do we need a tech solution for this? With more fields to fill in?

Before making the interface more complicated, I'd wait to see: if, where
and for whom this is a problem.
If it is, maybe we just want an administrator to be able to pull out per
user a list recent changes from the database?
So we can ask about it in reflection cafe?

jonas.



*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#8
