### ISSUE TITLE
Reassigning an experience listing to a different user

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe-old#55]
We have a few situations where a user accidentally signed up for two accounts and we want to merge there accounts. The problem is there is no way for us to transfer an experience listing to another user. What would be involved in building this feature out?

**Comment by jonaspiet** [comment]
this sounds like an exotic situation...
can we / the user not just copy-paste into a new listing under the chosen
user name? Instead of building a bespoke solution for this?

jonas.


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by lisajoytrick** [comment]
There are a couple situations right now where we could use this feature, but you're right, we can also do this manually, although it takes some time. I would be curious to get a quote from Sam so we can compare the development cost with team time savings.

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#9
