### ISSUE TITLE
Wishlist / Bookmark

### ISSUE THREAD

**Issue by samuelreh** [InWithForward/sharetribe-old#61]
Bookmark / wishlist different experiences/listings. Send data to mixpanel as well. Display to list to users.

**Comment by jonaspiet** [comment]
(Like AirBnB) A user can bookmark / mark an experience as 'favorite'. Marked experiences are collected on a wishlist that is public.

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#11
