### ISSUE TITLE
Report engagement: data to Mixpanel

### ISSUE THREAD

**Issue by samuelreh** [InWithForward/sharetribe-old#65]
Report events and identifies to mixpanel.

Get engagement data out of sharetribe, into Mixpanel.
Examples of info to display (Jonas and LJ need to make a selection here):

Host and Kudoer role:
  ~~Users last login (date & time)~~
  Response speed (average of how quickly they message back in message centre)
  Response rate (% of answered messages)
  % of profile listing filled in
  ~~# of experiences gone on~~
  ~~# of reviews written~~
  quality of review

Kudoer role:
~~number of changes in 'about me' section (and changes)~~

Host role:
  ~~# of experiences created~~
  ~~# experiences hosted~~
  ~~# of upcoming availability slots in calendar~~
  % of experience listing filled in

The idea is to first pull these numbers into Mix panel first, and see which ones are most interesting. Then we can make a choice on the metrics to display on user profile (feature #66).

Metric:
Positive mental health / hopefullness + Optimism / Kudoer participation in experiences
Decrease in stigma / Exposure / How much time hosts spends with Kudoers

**Comment by jonaspiet** [comment]
Get engagement data out of sharetribe, into Mixpanel.
Examples of info we'd like displayed (Jonas and LJ need to make a selection here):

Host and Kudoer role:
  Users last login (date & time)
  Response speed (average of how quickly they message back in message centre)
  Response rate (% of answered messages)
   % of profile listing filled in
  # of experiences gone on
  # of reviews written
  quality of review

Host role:
  # of experiences created
  # experiences hosted
  # of upcoming availability slots in calendar
  % of experience listing filled in

The idea is to first pull these numbers into Mix panel first, and see which ones are most interesting. Then we can make a choice on the metrics to display on user profile (feature #66).

Metric:
Positive mental health / hopefullness + Optimism / Kudoer participation in experiences
Decrease in stigma / Exposure / How much time hosts spends with Kudoers

**Comment by samuelreh** [comment]
Setup Mixpanel client side snippet: 0.5 hr
Setup Mixpanel for identifying logged in users: 0.5 hr
Update user properties on profile update (from admin or user settings): 0.5 hr

I say we start with these metrics and move on from there, I estimated about 15 min per metric:

Some events to track initially:
- Track when experience is attended 0.25hr
- Track when feedback is given ( positive or negative ) 0.25hr
- Track when About me field changes ( with value of field before and after change ) 0.25hr
- Track when listing is created 0.25hr
- Track when experience is hosted 0.25hr

**Comment by jonaspiet** [comment]
Great, let's do it!


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by lisajoytrick** [comment]
I'm pretty sure that mixpanel is showing activity as "experience attended" when the user has only requested the experience. For instance one user as apparently attended 5 experiences within a 20 minute period.

<img width="620" alt="screen shot 2016-04-14 at 2 28 52 pm" src="https://cloud.githubusercontent.com/assets/14365107/14544339/6bc0c46e-024d-11e6-86dd-b87aade93384.png">

**Comment by samuelreh** [comment]
@lisajoytrick weird, is it possible those were completed by an admin? Also, current times are set by Mixpanel, which is not ideal, so I changed it so we pass in the time from the application. This will make the times more accurate.

**Comment by lisajoytrick** [comment]
I've tested this some more and I'm more confident now that it is registering "experience attended" and "experience hosted" from the moment when someone "requests" or 'receives a request" rather then from the point that an experience is marked as completed. 

This also means that when an experience is booked by admin without requesting it's not showing up in mixpanel. I will test further to see if an admin-booked experience that is marked as complete ends up showing up.

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#13
