### ISSUE TITLE
Report engagement: activity stream on profile

### ISSUE THREAD

**Issue by samuelreh** [InWithForward/sharetribe-old#66]
As a user, I'm able to see stats about my engagement with the catalogue. 
For examples of info we'd like displayed (Jonas and LJ need to make a selection here): see feature #65  
We'll get the data in Mixpanel first - to see what's worth feeding back to users.

Metric:
Positive mental health / hopefullness + Optimism / Kudoer participation in experiences
Decrease in stigma / Exposure / How much time hosts spends with Kudoers

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#14
