### ISSUE TITLE
Record reflection cafe attendance in Mixpanel

### ISSUE THREAD

**Issue by samuelreh** [InWithForward/sharetribe-old#68]
Nice to have. 
So we can combine with other engagement data per user, as well as aggregated numbers.
Can we get this from Envoy?

Metric:
Positive mental health / hopefullness + Optimism / Kudoer participation in experiences
Decrease in stigma / Exposure / How much time hosts spends with Kudoers

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#15
