### ISSUE TITLE
Choose learning extension (also called "take home challenge")

### ISSUE THREAD

**Issue by samuelreh** [InWithForward/sharetribe-old#69]
On completion of experience add to feedback message 3 assignments, a Kudoer has to choose one of. 
These assignments are fields from listing of that experience.
 
After X amount of time, user is be prompted to mark if they have completed it or not. This is an email send to Kudoer and circle.

**Comment by lisajoytrick** [comment]
How I understand this feature request: 

MVP version to be completed by Jan 31
> 24 hours after marking experience as complete, a message goes to kudoer with 3 learning extensions listed. These are pulled out from the experience listing fields of the experience they went on. If some are missing, they only get 1 or 2 options. If no fields are completed, no message goes out.*
*<i>Ideally, admin/host would be triggered that no learning extensions could be sent because they were missing in the listing so we can follow up with the host and help get these set up</i>

version 2.0
> additional message goes out 48 hours after experience (and displays when user logs in to sharetribe) that asks which learning extension was completed, records the completion of the extension (in user activity) and gives them a chance to provide a quote or a bit of explanation about what happened or what they learned (simple text field)

**Comment by jonaspiet** [comment]
Guys, I have removed priority for this feature. 
I want to focus all development on the online profile / dashboard. 

We're not working on the take home exercizes right now, so let's pauze this feature.
Thanks!

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#16
