### ISSUE TITLE
Automatically show media file of completed experiences on profile page

### ISSUE THREAD

**Issue by samuelreh** [InWithForward/sharetribe-old#70]
In this feature, the completed experience media file is auto uploaded from the S3 Server to user's profile page. Along with the media file the feedback a kudoer gave a host would display beside the file.

. . . . . . . . . . . . . . . . . . . . .
to be discussed with mobile app developer:
> What format should it be in (mp4? mov? does it matter?)
> naming convention with username or something that should be used for the media file?
> meta data for media file, to upload in right place?

**Comment by lisajoytrick** [comment]
In this feature, the completed experience media file is auto uploaded from the S3 Server to user's profile page. Along with the media file the feedback a kudoer gave a host would display beside the file.

What format should it be in (mp4? mov? does it matter?)
Is there a naming convention with username or something that should be used for the media file?

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#17
