### ISSUE TITLE
Experience confirmation: Add to google calendar 

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe-old#74]
It would be nice if when the confirmation & reminder emails are received, there was an easy way for the event to be added to the user's calendar. See screenshots for suggested placement and some examples from other apps.

<img width="846" alt="screen shot 2016-01-21 at 3 18 24 pm" src="https://cloud.githubusercontent.com/assets/14365107/12497891/819a7190-c053-11e5-87c6-9278f291d1ab.png">
<img width="588" alt="screen shot 2016-01-20 at 5 10 05 pm" src="https://cloud.githubusercontent.com/assets/14365107/12497890/81999e5a-c053-11e5-8e71-71de721144ad.png">
<img width="716" alt="screen shot 2016-01-19 at 9 13 28 pm" src="https://cloud.githubusercontent.com/assets/14365107/12497892/81a89680-c053-11e5-90b4-3c1c969547a7.png">

**Comment by AndieFro** [comment]
This was brought up again today - Not this exact issue but realted to synching with calendars. Right now we are manually adding experiences to the 'kudoer & Circle interactions' calendar. Is there a way to have them automatically addded to this google calendar once a booking is confirmed?

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#19
