### ISSUE TITLE
request for admin role but not receiving new user emails

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe-old#88]
Can a user have admin access but not receive the notification emails for 'new user'?

**Comment by jonaspiet** [comment]
Quick fixes:
1) we can have a new admin account that is linked to a shared email address, e.g. hello@kudoz.ca. The login details of this account can be shared by multiple people.

2) we can share login details of an existing admin user (me?) with others.

**Comment by AndieFro** [comment]
@Jonas, I don't think that will work because we still need individual identity on the site, especially when we are contacting other users (Kudoers).

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#22
