### ISSUE TITLE
Wishlist changes to "view listings" admin page

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe-old#92]
Can we add the following columns to the “view listings” admin page 

listing created
- date 
- date 

listing updated
- date 
- date 

Change “author” column title to “host”  & can that column be a sortable column?

Make the "what's missing" column sortable.

Add a "availability" column that shows either the number of available timeslots come up or yes/no if there is availability in the calendar

Also, what does Invisible and searchable mean? Should we be using that field for adding keywords instead of the current keywords field in the listing?

**Comment by jonaspiet** [comment]
Hi Lisa, 'invisibale and searchable' was made as a shortcut for us to tag
experiences with kudoers names - so we could pull up a selection by adding
their name in the search field

it's currently not used


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#23
