### ISSUE TITLE
Welcome email for users - based on roles?

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe-old#93]
How much trouble would it be to have two welcome emails depending on the role a user chooses? 

And, to make an auto welcome email go out to the user when they are assigned the other role (ie: when a kudoer becomes a host the get the host welcome email?)

Alternatively we try to keep the welcome email generic enough to be relevant for both user types.

**Comment by samuelreh** [comment]
I would keep the generic email for now. It's not too hard, but would require several hours of dev.

**Comment by jonaspiet** [comment]
This issue was moved to jonaspiet/sharetribe-private#24
